### ISSUE TITLE
Extend parser with simplified 'as' operator

### ISSUE THREAD

**Issue by sshine** [sshine/hs-jq#25]
In [jq Distilled](https://github.com/fadado/JBOL/blob/master/doc/JQ-Distilled.md#schematic-syntax-for-special-constructs), the `as` operator is described.

Initially it would be convenient if hs-jq supported the most basic

```
term as $var
```

While the original jq parser does not allow `term as $var` without a subsequent `| ...` (the [JBOL grammar](https://github.com/fadado/JBOL/blob/master/doc/JQ-language-grammar.md) specifically says `Term "as" Pattern '|' Exp`), hs-jq takes the approach of parsing this and rejects programs in which `| ...` in a later validation phase not yet written.

The task is:
- [x] Extend the parser so it handles `term as $var`
- [x] Rewrite the tests provided in cca304c so they test that what's being parsed is also correct.

**Comment by Kaptch** [comment]
Did you consider moving to alex and happy? Those complex structures are going to be difficult and error-prone to parse with (mega)parsec, as far as I can see.

**Comment by sshine** [comment]
I'm not sure what structures you think of as complex here.

I've viewed `as ...` as a postfix expression operator with a very low precedence.

Yes, I did consider alex + happy. Especially because of the ambiguity caused by operators.

I'm not sure what should be the driving arguments to migrate to alex + happy.

At this point I'd like a complete parser so that I can start writing more interesting generators and properties. I might also like to refactor the Megaparsec parser, to see if it can become more acceptable.

**Comment by sshine** [comment]
I'm open to migrating to Alex + Happy at some point after finishing the Megaparsec one, since then further work that depends on a parser can continue in parallel, and not much is missing for that to happen. In the meantime you are very welcome to look at #27 and #40.
