### ISSUE TITLE
Extend parser with escape sequences in strings

### ISSUE THREAD

**Issue by sshine** [sshine/hs-jq#3]
JSON and jq don't support control characters in strings, and only allows for certain escape sequences.

```
$ echo -e '"\n"' | jq .
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 1
```

Basic positive tests for escape sequences and negative tests for control characters in strings exist.

- [x] Extend the parser with the ability to parse escape sequences.
- [x] Write a Hedgehog generator for `'u' hex hex hex hex` escape sequences.
- [x] Write a Hedgehog property that uses this generator.

Available escape sequences from https://www.json.org:

```
escape
    '"'
    '\'
    '/'
    'b'
    'f'
    'n'
    'r'
    't'
    'u' hex hex hex hex

hex
    digit
    'A' . 'F'
    'a' . 'f'
```

**Comment by Eckankar** [comment]
Sounds like a fun little task. :) I'll take a look at this.
