### ISSUE TITLE
Write Hedgehog generator and property-test for numbers

### ISSUE THREAD

**Issue by sshine** [sshine/hs-jq#5]
This issue can be addressed in parts.

An interesting exercise is to make a Hedgehog `Gen Text` that produces parseable JSON numbers. Such a generator can both be used to verify that jq parses numbers correctly which it probably does besides prefix `+` (#4), and verify that hs-jq behaves equivalently.

Currently, Megaparsec's built-in [`scientific :: Parser Scientific`](http://hackage.haskell.org/package/megaparsec-7.0.5/docs/Text-Megaparsec-Char-Lexer.html#v:scientific) is used with optional prefix `-`.

- [x] Find out how close Megaparsec's `scientific` matches JSON's numbers.
- [x] Write Hedgehog `Gen Text` for JSON numbers in test/Generators.hs.
- [ ] ~~Write property-based test: jq and hs-jq parse and produce the same number.~~

From https://www.json.org:

```
number
    integer fraction exponent

integer
    digit
    onenine digits
    '-' digit
    '-' onenine digits

digits
    digit
    digit digits

digit
    '0'
    onenine

onenine
    '1' . '9'

fraction
    ""
    '.' digits

exponent
    ""
    'E' sign digits
    'e' sign digits

sign
    ""
    '+'
    '-'
```

![number](https://user-images.githubusercontent.com/50879/65214784-8d83d200-daab-11e9-89d7-61d2c6131f23.png)

**Comment by JonathanLorimer** [comment]
Hey @sshine I would like to take a run at this if its alright. This is my first open source haskell issue, so please be patient! I noticed a couple things:

## Number Parser

~~I think that the number parser could be made more concise using megaparsecs [signed](http://hackage.haskell.org/package/megaparsec-7.0.5/docs/Text-Megaparsec-Char-Lexer.html#v:signed) in combination with `scientific`~~

~~I am making a branch right now to re-write the parser in terms of `signed` and test that it conforms to the spec~~

I just realized that `signed` allows '+' which is not the desired behaviour, so I think your existing parser is the correct implementation.

## Gen Text
I noticed that you already have a `numberGen :: Gen Text` test, I am assuming this issue wants the contributor to create this `sizedNumberGen :: Gen Text` function

## Property Based Test

My initial idea is to just do a round trip test converting a generated JSON number to a haskell `scientific` (provided the parser meets the spec) and then back to a JSON number.

---

I plan to start work on [this branch](https://github.com/JonathanLorimer/hs-jq/tree/property-test-for-numbers)

**Comment by JonathanLorimer** [comment]
Do you have any objections to me pulling in `aeson` for the roundtripping? Unless you already have logic that pretty prints the AST back as JSON, but I didn't see that.

**Comment by sshine** [comment]
You are very welcome to stab at it. I've assigned you. I would recommend that you wait with submitting the PR until October 1st to make it count towards a Hacktoberfest t-shirt. :-) If you want feedback before then, you can either submit a comment here and I'll look at your branch, or if you don't care about the t-shirt, feel free to submit a PR whenever.

> I just realized that `signed` allows '+' which is not the desired behaviour

Yes, exactly.

> I noticed that you already have a `numberGen :: Gen Text` test,

Feel free to replace the stub `numberGen` with your solution.

The current one has `"..."` in it and isn't used for anything.

> I am assuming this issue wants the contributor to create this `sizedNumberGen :: Gen Text` function

I think it's okay to call it `numberGen` and make it respect the internal size parameter.

> Do you have any objections to me pulling in `aeson` for the roundtripping?

Do you mean as in: Create a `Gen Scientific` or `Gen Value` (where `Value` is from `aeson`) and `fmap pp` on it?

I suspect that won't be sufficient for coverage: I'd like that the generator tests the full syntactic span of JSON numbers, and generating an arbitrary `Scientific` won't preserve the formatting (e.g. `1e3` will become `1000`). For example, with uniform distribution pick whether it should have a sign or not, be a number with an integer part or not, and so on, so each syntactic variation is hit with some probability.

Let me know if I misunderstood something here.

> My initial idea is to just do a round trip test converting a generated JSON number to a haskell `scientific` (provided the parser meets the spec) and then back to a JSON number.

This sounds just right.

Since the current [`number :: Parser Scientific`](https://github.com/sshine/hs-jq/blob/master/src/Data/Aeson/Jq/Parser.hs#L190) uses Megaparsec's [`scientific`](http://hackage.haskell.org/package/megaparsec-7.0.5/docs/Text-Megaparsec-Char-Lexer.html#v:scientific) and just adds the sign, then

```haskell
parseExpr generatedNumber === fmap NumLit (readEither generatedNumber)
```

This depends on the assumption that Haskell and jq reduce JSON numbers to the same canonical form. This is a good enough property for now. If hs-jq should represent numbers in a syntax-preserving way so that we can eventually do

```
$ hs-jq -n 1e3
1e3
```

we could make an even stronger property test. Since there are a lot of complicating factors wrt. arithmetic, and since it'd break compatibility with jq before any level of compatibility is reached, that's not a priority right now.

**Comment by sshine** [comment]
Just to be clear: I don't mind that you include `aeson` as a dependency if that helps.

But I'm not sure that it does; feel free to pick between explaining or demonstrating that it does.

We are, essentially, property-testing that Megaparsec's [`scientific`](https://hackage.haskell.org/package/megaparsec/docs/Text-Megaparsec-Char-Lexer.html#v:scientific) with the extra prefix `-` parses all JSON numbers, which is not in itself unreasonable to assume. But the generator will play a bigger role in testing the total syntax of jq, which makes it particularly useful.

**Comment by JonathanLorimer** [comment]
Right, the approach I was thinking of was something like this

```haskell
hprop_NumLit :: Property
hprop_NumLit = property $ do
  genNum <- forAll $ numberGen

  let roundTrip (NumLit n) = genNum === (Text.pack $ show n)

  either
    (\_ -> failure)
    roundTrip
    (parseExpr genNum)
```
obviously this fails because just showing a scientific will give you `"0.0"` when the input is `"0"`

so I was thinking of converting the scientific to JSON and comparing it with the input, but thinking about it, this won't work either.

But I like your solution where we just compare them as numbers. I am working on building a sized generator, and a generator for scientific notation

**Comment by JonathanLorimer** [comment]
I think you are right though, bringing in aeson seems unnecessary

**Comment by JonathanLorimer** [comment]
Okay, got a [draft PR](https://github.com/sshine/hs-jq/pull/8/files) up that is pretty rough, but working. 

I am going to add sized numbers and scientific notation next. Thanks for the guidance!

**Comment by JonathanLorimer** [comment]
Alright, I think the work I have done covers the minimal case that parsing a `jq` number is equivalent to a haskell representation of that number. You can check out my work in the draft PR.

**Comment by sshine** [comment]
In summary, to answer the first question:
- Text.Megaparsec's `scientific` doesn't handle `.1`. (Test cases in #11)
- Data.Scientific's `Scientific` doesn't handle exponents beyond size `Int`, causing hs-jq to throw a run-time exception when jq produces:
  ```
  $ jq -n 1e340282366920938463463374607431768211456 # 2^128
  1.7976931348623157e+308
  ```

As for the third item, "Write property-based test: jq and hs-jq parse and produce the same number," this task is postponed until hs-jq can parse numbers a little better.
